[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.13", features = ["derive"] }
md5 = "0.7.0"
regex = "1.5.5"
fancy-regex = "0.10.0"
